# Generated by Django 3.2.16 on 2022-12-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_post_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='plant_level',
            field=models.CharField(choices=[('1', 'Super hearty (it will survive anyone!)'), ('2', 'Needs minor super vision, like a young adult'), ('3', 'Must be checked up on at least once a week'), ('4', 'Fussy, needs constant attention')], default='1', max_length=250),
        ),
        migrations.AddField(
            model_name='plant',
            name='plant_light',
            field=models.CharField(choices=[('BRIGHT', 'Bright, indirect light required'), ('DIRECT', 'Direct light required'), ('LOW', 'Low light required'), ('MEDIUM', 'Medium light required')], default='1', max_length=250),
        ),
        migrations.AddField(
            model_name='plant',
            name='plant_thirst',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
