# Generated by Django 3.2.16 on 2022-12-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20221207_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plant_thirst',
            field=models.DecimalField(decimal_places=0, max_digits=1, null=True),
        ),
    ]
