# Generated by Django 3.2.16 on 2022-12-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_plant_plant_thirst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
    ]
